services:
  web:
    build: .
    container_name: help50_web
    depends_on:
      - mysql
    environment:
      APPLICATION_ENV: dev
      DB_HOST: mysql
      DB_NAME: help50
      DB_PASS: crimson
      DB_USER: root
    links:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - .:/srv/www
  mysql:
    container_name: help50_mysql
    image: mysql
    environment:
      MYSQL_DATABASE: help50
      MYSQL_ROOT_PASSWORD: crimson
version: "2"
